# Generated by Django 5.2.8 on 2025-11-20 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('tipo_aeronave', models.CharField(choices=[('AVION', 'Avión'), ('HELICOPTERO', 'Helicóptero')], max_length=15)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad_kg', models.IntegerField()),
                ('horas_vuelo', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('tipo_cliente', models.CharField(choices=[('NATURAL', 'Persona Natural'), ('EMPRESA', 'Empresa')], max_length=10)),
                ('direccion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('licencia', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('tipo_transporte', models.CharField(choices=[('TERRESTRE', 'Terrestre'), ('AEREO', 'Aéreo')], max_length=10)),
                ('distancia_km', models.FloatField()),
                ('tiempo_estimado', models.DurationField()),
                ('costo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('tipo_vehiculo', models.CharField(choices=[('CAMION', 'Camión'), ('FURGON', 'Furgón'), ('BUS', 'Bus'), ('VAN', 'Van')], max_length=10)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad_kg', models.IntegerField()),
                ('año', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo_carga', models.CharField(choices=[('FRAGIL', 'Frágil'), ('PELIGROSA', 'Peligrosa'), ('GENERAL', 'General'), ('REFRIGERADA', 'Refrigerada')], max_length=15)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_declarado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dimensiones', models.CharField(help_text='Largo x Ancho x Alto en cm', max_length=50)),
                ('requiere_refrigeracion', models.BooleanField(default=False)),
                ('instrucciones_especiales', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('certificacion', models.CharField(max_length=50)),
                ('horas_vuelo', models.IntegerField(default=0)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('aeronave_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.aeronave')),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_despacho', models.DateTimeField(auto_now_add=True)),
                ('fecha_estimada_entrega', models.DateTimeField()),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado'), ('EN_RUTA', 'En Ruta'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=10)),
                ('costo_envio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('codigo_seguimiento', models.CharField(max_length=20, unique=True)),
                ('observaciones', models.TextField(blank=True)),
                ('aeronave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.aeronave')),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.carga')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.cliente')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.conductor')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('piloto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.piloto')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.ruta')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='conductor',
            name='vehiculo_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.vehiculo'),
        ),
    ]
