# Generated by Django 5.2.8 on 2025-11-20 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_carga', models.CharField(max_length=15)),
                ('descripcion', models.TextField(blank=True)),
                ('distancia_km', models.FloatField(default=0)),
                ('costo_por_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nombre_cliente', models.CharField(blank=True, max_length=100)),
                ('email_cliente', models.EmailField(blank=True, max_length=254)),
                ('telefono_cliente', models.CharField(blank=True, max_length=15)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('codigo_seguimiento', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('despacho', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.despacho')),
            ],
        ),
    ]
